(() => {
  const $=id=>document.getElementById(id), player=$('playerView'), drawer=$('gameMenuDrawer');
  if(!player||!drawer)return;
  const APP_DB='retro-pocket-db',APP_DB_VERSION=2,ROM_STORE='roms',LAST_ROM='last-rom';
  const STUDY_DB='retro-pocket-study-db',STUDY_DB_VERSION=1,INDEX_STORE='indexes',TRANS_STORE='translations';
  const KNOWN_EB_SHA256='a8fe2226728002786d68c27ddddf0b90a894db52e4dfe268fdf72a68cae5f02e';
  const PTR_TABLES=[0x8CDED,0x8D1ED,0x8D5ED];
  const COMMON=new Set('the and you to of a i is it in that this for on with have do not are be your my me we he she they what where who how why can will would could should want like get go got from at as if but or so just no yes here there one all out up down now then know think good come see take give make going about really please thank hello well let right very much little more some when time look need him her them our us his their into back away still even maybe sure okay'.split(' '));
  const STOP=new Set('the a an and or but if then to of in on at for from with as is are was were be been being this that these those it its i you he she we they my your his her our their me him us them do does did have has had can could will would should may might not no yes just very really there here'.split(' '));
  const state={busy:false,index:null,romHash:'',selected:null,ngram:null,live:false,liveBusy:false,liveTimer:null,lastLiveKey:'',autoTranslate:true};

  function injectMenuEntry(){const list=drawer.querySelector('.feature-menu-list');if(!list||$('englishStudyOpen'))return;const b=document.createElement('button');b.id='englishStudyOpen';b.type='button';b.innerHTML='<span><b>📚 英語学習</b><small>ROM解析・ライブ字幕</small></span><i>›</i>';const reload=$('reloadGame');reload?list.insertBefore(b,reload):list.appendChild(b);b.onclick=()=>{closeSettings();openStudy();};}
  function closeSettings(){drawer.classList.add('hidden');$('menuBackdrop')?.classList.add('hidden');document.body.classList.remove('menu-open');}
  function ensureSubtitle(){if($('liveStudySubtitle'))return;const el=document.createElement('button');el.id='liveStudySubtitle';el.type='button';el.className='live-study-subtitle hidden';el.innerHTML='<span id="liveStudyEn">英語字幕を待っています</span><strong id="liveStudyJa">ライブ字幕をONにすると表示されます</strong><small id="liveStudyConfidence"></small>';el.onclick=()=>{if(state.selected)openStudy(true);};player.appendChild(el);}
  function ensureStudyUi(){if($('englishStudySheet'))return;const wrap=document.createElement('div');wrap.id='englishStudySheet';wrap.className='study-sheet hidden';wrap.innerHTML=`<div class="study-backdrop" data-study-close></div><section class="study-card"><header><div><small>ENGLISH STUDY · PRIVATE</small><strong>EarthBound 英語学習</strong></div><button type="button" data-study-close>×</button></header><div class="study-body">
  <div class="study-privacy"><b>🔒 端末内解析</b><span>ROM・抽出台詞・保存データはGitHubへ送信しません。</span></div>
  <div class="study-db-card"><div><small>ROM台詞データベース</small><strong id="studyDbStatus">未作成</strong><span id="studyDbMeta">保存済みROMから作成できます</span></div><button id="studyBuildDb" type="button">ROMを解析</button></div>
  <section class="live-study-card"><div><small>LIVE SUBTITLE</small><strong>ゲーム中の台詞を自動検出</strong><span id="liveStudyStatus">停止中</span></div><button id="liveStudyToggle" type="button">OFF</button></section>
  <label class="study-check"><input id="liveAutoTranslate" type="checkbox" checked><span>一致した英文を自動で日本語訳する</span></label>
  <p class="study-note">一般OCRは使いません。EmulatorJSの実行中ステートからEarthBound文字列候補を読み、端末内ROMから作った台詞DBと照合します。</p>
  <div class="study-search"><label>台詞を検索</label><input id="studySearch" type="search" placeholder="例: Pokey / want to / meteorite" autocomplete="off"><small>ROMから抽出した英語台詞を検索できます。</small></div>
  <div id="studyMatches" class="study-matches"><div class="study-empty">まず「ROMを解析」を押してください</div></div>
  <section id="studyDetail" class="study-detail hidden"><label>英語原文</label><div id="studyEnglish" class="study-output"></div><button class="study-small" id="studyTranslate" type="button">この英文を日本語に翻訳</button><p class="study-network-note">翻訳時のみ選択した英文を外部翻訳サービスへ送ります。ROMや画面画像は送りません。</p><label>日本語訳</label><div id="studyJapanese" class="study-output">まだ翻訳していません</div><label>学習候補の単語</label><div id="studyWords" class="study-words"></div></section>
  </div></section>`;player.appendChild(wrap);wrap.querySelectorAll('[data-study-close]').forEach(el=>el.onclick=closeStudy);$('studyBuildDb').onclick=buildDialogueDb;$('studySearch').oninput=renderSearch;$('studyTranslate').onclick=()=>state.selected&&translateItem(state.selected,false);$('liveStudyToggle').onclick=toggleLive;$('liveAutoTranslate').onchange=e=>state.autoTranslate=e.target.checked;}
  async function openStudy(fromSubtitle=false){ensureStudyUi();$('englishStudySheet').classList.remove('hidden');await restoreIndex();if(fromSubtitle&&state.selected)showDetail(state.selected);}
  function closeStudy(){$('englishStudySheet')?.classList.add('hidden');}
  function setDbStatus(main,meta=''){if($('studyDbStatus'))$('studyDbStatus').textContent=main;if($('studyDbMeta'))$('studyDbMeta').textContent=meta;}

  function openAppDb(){return new Promise((res,rej)=>{const r=indexedDB.open(APP_DB,APP_DB_VERSION);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
  async function loadCachedRom(){const db=await openAppDb(),rec=await new Promise((res,rej)=>{const tx=db.transaction(ROM_STORE,'readonly'),q=tx.objectStore(ROM_STORE).get(LAST_ROM);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);});db.close();return rec?new File([rec.data],rec.name,{type:rec.type||'application/octet-stream',lastModified:rec.lastModified||Date.now()}):null;}
  function openStudyDb(){return new Promise((res,rej)=>{const r=indexedDB.open(STUDY_DB,STUDY_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(INDEX_STORE))db.createObjectStore(INDEX_STORE);if(!db.objectStoreNames.contains(TRANS_STORE))db.createObjectStore(TRANS_STORE);};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
  async function studyGet(store,key){const db=await openStudyDb(),v=await new Promise((res,rej)=>{const tx=db.transaction(store,'readonly'),q=tx.objectStore(store).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);});db.close();return v;}
  async function studyPut(store,key,val){const db=await openStudyDb();await new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(val,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});db.close();}
  async function sha256(bytes){const h=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  function stripHeader(u8){return u8.length%1024===512?u8.subarray(512):u8;}
  function isStoredPrintable(b){const c=b-0x30;return c>=0x20&&c<=0x7e;}
  function cleanEnglish(s){return s.replace(/\s+/g,' ').trim().replace(/\s+([,.!?;:])/g,'$1');}
  function englishScore(s){if(s.length<7)return-99;const letters=(s.match(/[A-Za-z]/g)||[]).length,spaces=(s.match(/ /g)||[]).length,words=(s.toLowerCase().match(/[a-z']+/g)||[]),common=words.reduce((n,w)=>n+(COMMON.has(w)?1:0),0),vowels=(s.match(/[aeiouy]/gi)||[]).length,vr=vowels/Math.max(1,letters);return common*3+Math.min(letters,50)/20+spaces*.25-(vr>.18&&vr<.7?0:3);}
  function decodeBlock(rom,off){let p=off,out='',bad=0;for(let n=0;p<rom.length&&n<1200;n++,p++){const b=rom[p];if(b===0)break;if(isStoredPrintable(b)){out+=String.fromCharCode(b-0x30);bad=0;}else if(b<0x20&&bad<4){out+=' ';bad++;}else break;}return cleanEnglish(out);}
  function resolvePtr(rom,table,id){const p=table+id*4;if(p+3>=rom.length)return-1;const addr=rom[p]|(rom[p+1]<<8),bank=rom[p+2],off=((bank&0x3f)<<16)|addr;return off>=0&&off<rom.length?off:-1;}
  function addCandidate(map,text,offset,source,bonus=0){text=cleanEnglish(text);const sc=englishScore(text)+bonus;if(text.length<7||sc<5)return;const key=text.toLowerCase(),old=map.get(key);if(!old||sc>old.score)map.set(key,{text,offset,source,score:sc});}
  function extractDialogue(rom){const map=new Map();let pointerHits=0;for(let t=0;t<PTR_TABLES.length;t++)for(let id=0;id<256;id++){const off=resolvePtr(rom,PTR_TABLES[t],id);if(off<0)continue;const text=decodeBlock(rom,off);if(englishScore(text)>=5){pointerHits++;addCandidate(map,text,off,`ptr${t}:${id}`,2);}}for(let i=0;i<rom.length;){if(!isStoredPrintable(rom[i])){i++;continue;}const start=i;let out='';while(i<rom.length&&isStoredPrintable(rom[i])&&out.length<500){out+=String.fromCharCode(rom[i]-0x30);i++;}addCandidate(map,out,start,'scan');if(i===start)i++;}return{items:[...map.values()].sort((a,b)=>b.score-a.score).slice(0,3000),pointerHits};}
  async function buildDialogueDb(){if(state.busy)return;state.busy=true;$('studyBuildDb').disabled=true;setDbStatus('ROMを解析中…','端末内だけで処理しています');try{const f=await loadCachedRom();if(!f)throw new Error('保存済みROMがありません');const raw=await f.arrayBuffer(),hash=await sha256(raw),rom=stripHeader(new Uint8Array(raw)),result=extractDialogue(rom),rec={hash,name:f.name,size:f.size,createdAt:Date.now(),knownEarthBound:hash===KNOWN_EB_SHA256,pointerHits:result.pointerHits,items:result.items};await studyPut(INDEX_STORE,hash,rec);await studyPut(INDEX_STORE,'last',rec);state.index=rec;state.romHash=hash;buildNgramIndex();setDbStatus(`${rec.items.length.toLocaleString()}件を抽出`,`${rec.knownEarthBound?'EarthBound USA確認済み':'ROM解析済み'} · ポインタ ${rec.pointerHits}件`);renderSearch();}catch(e){console.warn(e);setDbStatus('解析できませんでした',e.message||'ROMを確認してください');}finally{state.busy=false;$('studyBuildDb').disabled=false;}}
  async function restoreIndex(){if(state.index?.items?.length)return;try{const rec=await studyGet(INDEX_STORE,'last');if(rec?.items?.length){state.index=rec;state.romHash=rec.hash;buildNgramIndex();setDbStatus(`${rec.items.length.toLocaleString()}件を保存済み`,`${rec.knownEarthBound?'EarthBound USA':'ROM'} · ${new Date(rec.createdAt).toLocaleString('ja-JP')}`);renderSearch();}}catch(e){console.warn(e);}}
  function wordsOf(s){return (s.toLowerCase().match(/[a-z']+/g)||[]).filter(w=>w.length>1);}
  function buildNgramIndex(){const map=new Map();(state.index?.items||[]).forEach((item,id)=>{const w=wordsOf(item.text);for(let i=0;i<=w.length-3;i++){const g=w.slice(i,i+3).join(' ');if(g.length<8)continue;let a=map.get(g);if(!a){a=[];map.set(g,a);}if(a.length<12)a.push(id);}});state.ngram=map;}

  function renderSearch(){const box=$('studyMatches');if(!box)return;if(!state.index?.items?.length){box.innerHTML='<div class="study-empty">まず「ROMを解析」を押してください</div>';return;}const q=($('studySearch')?.value||'').trim().toLowerCase();let list=q?state.index.items.filter(x=>x.text.toLowerCase().includes(q)):state.index.items.slice(0,12);list=list.slice(0,40);box.innerHTML=list.length?'':'<div class="study-empty">一致する台詞がありません</div>';for(const item of list){const b=document.createElement('button');b.type='button';b.className='study-match';b.innerHTML=`<span>${escapeHtml(item.text.slice(0,220))}${item.text.length>220?'…':''}</span><small>ROM 0x${item.offset.toString(16).toUpperCase()} · ${item.source}</small>`;b.onclick=()=>showDetail(item);box.appendChild(b);}}
  async function showDetail(item){state.selected=item;$('studyDetail')?.classList.remove('hidden');if($('studyEnglish'))$('studyEnglish').textContent=item.liveText||item.text;if($('studyJapanese'))$('studyJapanese').textContent='翻訳を取得中…';renderWords(item.liveText||item.text);const cached=await studyGet(TRANS_STORE,textKey(item.liveText||item.text));if(cached?.ja)$('studyJapanese').textContent=cached.ja;else $('studyJapanese').textContent='まだ翻訳していません';}
  function textKey(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(state.romHash||'rom')+':'+(h>>>0).toString(16);}
  async function translateText(text){const key=textKey(text),cached=await studyGet(TRANS_STORE,key);if(cached?.ja)return cached.ja;const q=text.slice(0,480),r=await fetch('https://api.mymemory.translated.net/get?q='+encodeURIComponent(q)+'&langpair=en|ja');if(!r.ok)throw new Error('translate');const j=await r.json(),ja=j?.responseData?.translatedText||'';if(ja)await studyPut(TRANS_STORE,key,{ja,time:Date.now()});return ja;}
  async function translateItem(item,silent=false){const text=item.liveText||item.text;if(!silent&&$('studyJapanese'))$('studyJapanese').textContent='翻訳しています…';try{const ja=await translateText(text);if(!silent&&$('studyJapanese'))$('studyJapanese').textContent=ja||'翻訳結果なし';return ja;}catch(e){console.warn(e);if(!silent&&$('studyJapanese'))$('studyJapanese').textContent='翻訳を取得できませんでした';return'';}}
  function renderWords(text){const box=$('studyWords');if(!box)return;const uniq=[...new Set(wordsOf(text).filter(w=>w.length>2&&!STOP.has(w)))].slice(0,14);box.innerHTML=uniq.length?uniq.map(w=>`<span>${escapeHtml(w)}</span>`).join(''):'<span>候補なし</span>';}

  function toggleLive(){state.live=!state.live;const b=$('liveStudyToggle');if(b){b.textContent=state.live?'ON':'OFF';b.classList.toggle('active',state.live);}setLiveStatus(state.live?'監視を開始します…':'停止中');ensureSubtitle();$('liveStudySubtitle')?.classList.toggle('hidden',!state.live);if(state.live){restoreIndex().then(()=>scheduleLive(100));}else{clearTimeout(state.liveTimer);state.liveTimer=null;}}
  function setLiveStatus(t){if($('liveStudyStatus'))$('liveStudyStatus').textContent=t;}
  function scheduleLive(ms=1100){clearTimeout(state.liveTimer);if(state.live)state.liveTimer=setTimeout(liveTick,ms);}
  async function liveTick(){if(!state.live)return;if(document.hidden||!state.index?.items?.length){setLiveStatus(!state.index?'ROM解析が必要です':'待機中');scheduleLive(1200);return;}const gm=window.EJS_emulator?.gameManager;if(!gm?.getState){setLiveStatus('エミュレータ待機中');scheduleLive(1200);return;}if(state.liveBusy){scheduleLive(800);return;}state.liveBusy=true;try{const raw=await Promise.resolve(gm.getState()),bytes=raw instanceof Uint8Array?raw:new Uint8Array(raw),runs=scanStateStrings(bytes),match=matchRuns(runs);if(match){setLiveStatus(`一致度 ${Math.round(match.confidence*100)}%`);await presentLiveMatch(match);}else setLiveStatus('台詞を探しています…');}catch(e){console.warn('live subtitle',e);setLiveStatus('再試行中…');}finally{state.liveBusy=false;scheduleLive(1050);}}
  function scanStateStrings(bytes){const out=[];for(let i=0;i<bytes.length;){if(!isStoredPrintable(bytes[i])){i++;continue;}let j=i,s='';while(j<bytes.length&&isStoredPrintable(bytes[j])&&s.length<180){s+=String.fromCharCode(bytes[j]-0x30);j++;}s=cleanEnglish(s);if(s.length>=10&&englishScore(s)>=4&&wordsOf(s).length>=3)out.push(s);i=Math.max(i+1,j);}return out.slice(0,220);}
  function matchRuns(runs){if(!state.ngram)return null;let best=null;for(const run of runs){const w=wordsOf(run);if(w.length<3)continue;const votes=new Map();for(let i=0;i<=w.length-3;i++){const ids=state.ngram.get(w.slice(i,i+3).join(' '));if(!ids)continue;for(const id of ids)votes.set(id,(votes.get(id)||0)+1);}for(const [id,v] of votes){const item=state.index.items[id],iw=wordsOf(item.text),set=new Set(iw),shared=w.reduce((n,x)=>n+(set.has(x)?1:0),0),coverage=shared/Math.max(3,Math.min(w.length,iw.length)),confidence=Math.min(1,.45+v*.13+coverage*.35);if(v>=1&&shared>=3&&(!best||confidence>best.confidence))best={item,run,confidence};}}return best&&best.confidence>=.68?best:null;}
  async function presentLiveMatch(m){const text=cleanEnglish(m.run),key=textKey(text);if(key===state.lastLiveKey)return;state.lastLiveKey=key;const item={...m.item,liveText:text};state.selected=item;ensureSubtitle();$('liveStudySubtitle')?.classList.remove('hidden');$('liveStudyEn').textContent=text;$('liveStudyConfidence').textContent=`ROM照合 ${Math.round(m.confidence*100)}%`;$('liveStudyJa').textContent=state.autoTranslate?'翻訳中…':'タップして学習';if(state.autoTranslate){const ja=await translateItem(item,true);if(state.lastLiveKey===key)$('liveStudyJa').textContent=ja||'翻訳を取得できませんでした';}}
  function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

  ensureSubtitle();ensureStudyUi();injectMenuEntry();new MutationObserver(injectMenuEntry).observe(drawer,{childList:true,subtree:true});
})();